### PR TITLE
Move away from the component-based approach

### PR DESCRIPTION
**Pull request by niuage**

### CODE REVIEW

**Comment by niuage** [comment]
You'd use this new function like so:

```js
import { useKeypress } from 'vue3_keypress';
import { ref } from 'vue';
...

setup() {

    const someSuccessCallback = ({ keyCode }) => {
        // doSomething;
    }

    // When this ref value changes, event listeners will automatically be added/removed.
    // This is optional. If it's not passed to `useKeypress` via the `isActive` option,
    // then the event listeners will only be added/removed on onMounted/onUnmounted respectively.
    const dropdownOpened = ref(false);

    useKeypress({
        keyEvent: "keydown",
        keyBinds: [
          {
            keyCode: "down",
            success: () => incrementSelectedIndex(1),
            preventDefault: false // the default is true now
          },
          {
            keyCode: "up",
            success: ({ keyCode, modifiers }) => doSomethingWith();
          },
          {
            keyCode: "enter",
            success: someSuccessCallback
          },
          {
            keyCode: "tab",
            success: () => incrementSelectedIndex(1)
          },
          {
            keyCode: "tab",
            modifiers: ["shiftKey"],
            success: () => incrementSelectedIndex(-1)
          },
          {
            keyCode: "esc",
            success: () => close()
          }
        ],
        isActive: dropdownOpened
    });

    // It can be called multiple times
    useKeypress({
        keyEvent: "keyup",
        keyBinds: [...]
     });
}
```

@lupas Gotta change package.json, build, etc, but I'll let you chose how you want to name files, etc, in case you want to move forward with a solution close to this one.

**Comment by lupas** [comment]
Hey @niuage

This is awesome, thanks a lot for the PR - appreciate it!

I just did two commits to (1) migrate the module to Typescript, so I can bundle it with typescript and can automatically generate the types. (2) Add onWrong handler, (3) Updated the Demo & (4) Updated docs accordingly

One thing I don't like:
Why did you map some keys in "key_codes.js"? There are many keys missing, so if I want to handle a click on "E" (keyCode 69) I currently cannot do this. Why do we need this mapping and can't just expect the key codes to be entered instead of some strings?

Good reason for this decision?

What's missing before I'll merge:

- [X] Add Types
- [x] FIX: IF `isActive` is undefined, the listener is not set up -> should be option
- [x] FIX: Watcher in `isActive` seems not be be working for me in general
- [ ] Clear the "key_codes" mapping issue mentioned above
- [ ] Update docs after all the fixes

I like this approach much better than the component based approach, so I decided not to go with a "we provide both" approach, since every Vue project, even if they generally don't use the composition API, can implement a setup() function like so nevertheless.

I might be working on some of these things too, let's see if I can find the time.

br, Pascal

**Comment by lupas** [comment]
That's the reason why the modules are not loaded when isActive is missing...

Screenshot 2021-01-15 at 17 08 02

> [Vue warn]: onMounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

> [Vue warn]: onUnmounted is called when there is no active component instance to be associated with. Lifecycle injection APIs can only be used during execution of setup(). If you are using async setup(), make sure to register lifecycle hooks before the first await statement.

Trying to find the issue...

**Comment by lupas** [comment]
Okay so the `onMounted / onUnmounted`issue is only happening locally with `yarn link`, not when I actually publish the library. I published a beta version for testing `yarn add vue3-keypress@4.0.0-beta2`.

So that issue is not really an issue 💪 .

**Comment by lupas** [comment]
Fixed the isActive not working issue with `vue3-keypress@4.0.0-beta3`

Only the key_codes & docs issues to be fixed, then I will merge & release :)

**Comment by lupas** [comment]
Aaaand after closer looking at the code I realized that the keyCode is taken if no strings maps to a keycode ;-) so all good.

Are these keyCodes randomly defined by you our are these mapping something official?

**Comment by lupas** [comment]
Released all with [v4.0.0](https://github.com/lupas/vue3-keypress/releases/tag/v4.0.0)

**Pull request merged**
